### ISSUE TITLE
qgis 3.2.0 bug when selecting and splitting polygon with lines

### ISSUE THREAD

**Issue by majesticpdx** [bstroebl/DigitizingTools#37]
Hello, 

In Qgis 3.2, I'm receiving the following error when selecting polygons.

```
     WARNING    Traceback (most recent call last):
              File "C:\Users\****\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dttools.py", line 252, in enable level=QgsMessageBar.WARNING, duration = 10)
 AttributeError: type object 'QgsMessageBar' has no attribute 'WARNING'
```
Also while attempting to split a polygon with lines, I'm receiving the following error: 

```
     WARNING    Traceback (most recent call last):
              File "C:\Users\****\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dtsplitter.py", line 90, in process
              selGeom.transform(QgsCoordinateTransform(passiveCRSSrsid, projectCRSSrsid))
             TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
              overload 1: too many arguments
              overload 2: argument 1 has unexpected type 'int'
              overload 3: argument 1 has unexpected type 'int'
              overload 4: argument 1 has unexpected type 'int'
              overload 5: argument 1 has unexpected type 'int'
```

**Comment by bstroebl** [comment]
Already reported in #36 and fixed, please try the latest release

**Comment by majesticpdx** [comment]
Perfect, thanks.
