### ISSUE TITLE
Uncaught ImportError: cannot import name 'DtDualToolSelectPolygon' from 'dttools' (C:\Users\lindauju\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dttools.py)


### ISSUE THREAD

**Issue by lindauju** [bstroebl/DigitizingTools#49]
Konnte Erweiterung 'DigitizingTools' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/lindauju/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DigitizingTools\__init__.py", line 28, in classFactory
    from .digitizingtools import DigitizingTools
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/lindauju/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DigitizingTools\digitizingtools.py", line 38, in <module>
    import dtcutter
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\lindauju\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dtcutter.py", line 23, in <module>
    from dttools import DtDualToolSelectPolygon
ImportError: cannot import name 'DtDualToolSelectPolygon' from 'dttools' (C:\Users\lindauju\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dttools.py)

```
DigitizingTools 1.5.0, QGIS 3.4.11-Madeira on Windows 10

**Comment by bstroebl** [comment]
Closing due to lack of feeedback, problem solved assumed.
